trigger:
 none
pool:
  vmImage: ubuntu-latest
stages: 
- stage: dev
  displayName: test Terraform deployment
  variables:
    - group: "test"
  jobs:
  - deployment: test
    continueOnError: false
    environment: 'test'
    strategy:
     runOnce:
       deploy:
         steps:
         - checkout: self
         - template: template.yml

- stage: prod
  displayName: prod Terraform deployment
  variables:
    - group: "prod"
  jobs:
  - deployment: prod
    continueOnError: false
    environment: 'prod'
    strategy:
     runOnce:
       deploy:
        steps:
        - checkout: self
        - template: template.yml